version: '3.8'
services:
    spring-app:
        container_name: spring-app
        image: top-app:1
        build: .
        ports:
          - "8090:8090"
        depends_on:
          - postgres-db
        environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/topeducation
          - SPRING_DATASOURCE_USERNAME=postgres
          - SPRING_DATASOURCE_PASSWORD=gejromor77
          - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    postgres-db:
        container_name: postgres-db
        image: postgres:latest
        restart: always
        volumes:
          - ./data/db:/var/lib/postgresql/data
        ports:
          - "5432:5432"
        environment:
          POSTGRES_DB: topeducation
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: gejromor77