version: '3'
services:
    spring-app:
        container_name: spring-app
        image: top-app:1
        build: .
        ports:
          - "8080:8080"
        depends_on:
          - postgres-db
        environment:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/topeducation
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: gejromor77

    postgres-db:
        container_name: postgres_db
        image: postgres:latest
        ports:
          - "5432:5432"
        environment:
          POSTGRES_DB: topeducation
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: gejromor77